--- #YAML:1.0
name:                IO-Prompt
version:             0.997001
abstract:            Interactively prompt for user input
license:             ~
author:              
    - Damian Conway <DCONWAY@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Handle:                    0
    POSIX:                         0
    Term::ReadKey:                 0
    Test::More:                    0
    version:                       0
    Want:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
